version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6
    executor: python/default
    steps:
      - checkout
      - python/install-deps	
      - run:
          command: |
              pytest ./tests/
          name: Test

workflows:
  main:
    jobs:
      - build-and-test

