version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python36/default
    steps:
      - checkout
      - run:
          command: |
              pip install -U pip setuptools
              pip search tensorflow
              pip install -e "git+git@github.com:blue-oil/blueoil.git#egg=blueoil[cpu,test]"
              pytest ./
          name: Test

workflows:
  main:
    jobs:
      - build-and-test

